<a href="https://colab.research.google.com/github/dev-sincode/colab/blob/main/joins_in_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
left  =  pd.DataFrame( {'key':['A','B','C','D'], 'value': np.random.randn(4)} )
right  = pd.DataFrame( {'key':['E','A','B','C'], 'value': np.random.randn(4)} )

In [4]:
left

  key     value
0   A -0.408128
1   B -0.530763
2   C -1.207907
3   D -0.662159

In [5]:
right

  key     value
0   E  0.892758
1   A  0.607860
2   B -1.324240
3   C -0.646491

In [6]:
left.merge(right, on = 'key', how = 'inner')

  key   value_x   value_y
0   A -0.408128  0.607860
1   B -0.530763 -1.324240
2   C -1.207907 -0.646491

In [8]:
left.merge(right, on = 'key', how = 'outer')

  key   value_x   value_y
0   A -0.408128  0.607860
1   B -0.530763 -1.324240
2   C -1.207907 -0.646491
3   D -0.662159       NaN
4   E       NaN  0.892758

In [9]:
left.merge(right, on = 'key', how = 'left')

  key   value_x   value_y
0   A -0.408128  0.607860
1   B -0.530763 -1.324240
2   C -1.207907 -0.646491
3   D -0.662159       NaN

In [10]:
left.merge(right, on = 'key', how = 'right')

  key   value_x   value_y
0   E       NaN  0.892758
1   A -0.408128  0.607860
2   B -0.530763 -1.324240
3   C -1.207907 -0.646491